#### when we talk about handling the Duplicate values 
 - means mainly we drop the duplicate Values from the dataframe

In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("sample_data.csv")
df

    id          name   age country   gender
0    1      John Doe  29.0     USA     Male
1    1      John Doe  29.0     USA     Male
2    2    Jane Smith   NaN  Canada   Female
3    3          Alex   NaN     USA  Unknown
4    4  Maria Garcia  34.0   Spain   Female
5    5        Li Wei  27.0   China     Male
6    6           NaN  45.0   India   Female
7    7    Ahmed Khan  38.0     NaN     Male
8    8    Rachel Lee  29.0     USA   Female
9    9   Carlos Ruiz   NaN  Mexico      NaN
10  10   Emily Davis  31.0     USA      NaN

In [5]:
df.duplicated()
# To know the Duplicated Values

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [6]:
df

    id          name   age country   gender
0    1      John Doe  29.0     USA     Male
1    1      John Doe  29.0     USA     Male
2    2    Jane Smith   NaN  Canada   Female
3    3          Alex   NaN     USA  Unknown
4    4  Maria Garcia  34.0   Spain   Female
5    5        Li Wei  27.0   China     Male
6    6           NaN  45.0   India   Female
7    7    Ahmed Khan  38.0     NaN     Male
8    8    Rachel Lee  29.0     USA   Female
9    9   Carlos Ruiz   NaN  Mexico      NaN
10  10   Emily Davis  31.0     USA      NaN

In [7]:
df["country"].duplicated()

0     False
1      True
2     False
3      True
4     False
5     False
6     False
7     False
8      True
9     False
10     True
Name: country, dtype: bool

In [13]:
df["country"].duplicated()

0     False
1      True
2     False
3      True
4     False
5     False
6     False
7     False
8      True
9     False
10     True
Name: country, dtype: bool

    id          name   age country   gender
0    1      John Doe  29.0     USA     Male
1    1      John Doe  29.0     USA     Male
2    2    Jane Smith   NaN  Canada   Female
3    3          Alex   NaN     USA  Unknown
4    4  Maria Garcia  34.0   Spain   Female
5    5        Li Wei  27.0   China     Male
6    6           NaN  45.0   India   Female
7    7    Ahmed Khan  38.0     NaN     Male
8    8    Rachel Lee  29.0     USA   Female
9    9   Carlos Ruiz   NaN  Mexico      NaN
10  10   Emily Davis  31.0     USA      NaN

In [14]:
df[["country","gender"]].duplicated()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [20]:
#To check Duplicates Column Wise 
df.duplicated(subset=['country'])
df["country"].duplicated()

0     False
1      True
2     False
3      True
4     False
5     False
6     False
7     False
8      True
9     False
10     True
Name: country, dtype: bool

In [21]:
# To check the Duplicates row wise 
#df.T → transpose (columns become rows)
#Then duplicated() works row-wise

df.T.duplicated()

id         False
name       False
age        False
country    False
gender     False
dtype: bool

In [22]:
df

    id          name   age country   gender
0    1      John Doe  29.0     USA     Male
1    1      John Doe  29.0     USA     Male
2    2    Jane Smith   NaN  Canada   Female
3    3          Alex   NaN     USA  Unknown
4    4  Maria Garcia  34.0   Spain   Female
5    5        Li Wei  27.0   China     Male
6    6           NaN  45.0   India   Female
7    7    Ahmed Khan  38.0     NaN     Male
8    8    Rachel Lee  29.0     USA   Female
9    9   Carlos Ruiz   NaN  Mexico      NaN
10  10   Emily Davis  31.0     USA      NaN

In [23]:
# get Only Duplicate Rows 
df[df.duplicated()]

   id      name   age country gender
1   1  John Doe  29.0     USA   Male

In [25]:
df[df["name"].duplicated()]

   id      name   age country gender
1   1  John Doe  29.0     USA   Male

In [26]:
# Get All Duplicates (including first occurrence)
df[df.duplicated(keep=False)]

   id      name   age country gender
0   1  John Doe  29.0     USA   Male
1   1  John Doe  29.0     USA   Male

In [28]:
    # Check Row-wise vs Column-wise Summary
    #Row-wise duplicates count:
    
    df.duplicated().sum()

1

In [32]:
 # Column wise Duplicate Count 
df.T.duplicated().sum()

0

In [ ]:
Case	
Row-wise duplicates
df.duplicated()
Specific column	
df.duplicated(subset=['col'])
Column values	
df['col'].duplicated()
Column-wise duplicates
df.T.duplicated()
Get duplicate rows	
df[df.duplicated()]
Get all duplicates
df[df.duplicated(keep=False)]