In [2]:
import pandas as pd

In [3]:
data=pd.read_csv("sample_data.csv")

In [4]:
data

    id          name   age country   gender
0    1      John Doe  29.0     USA     Male
1    1      John Doe  29.0     USA     Male
2    2    Jane Smith   NaN  Canada   Female
3    3          Alex   NaN     USA  Unknown
4    4  Maria Garcia  34.0   Spain   Female
5    5        Li Wei  27.0   China     Male
6    6           NaN  45.0   India   Female
7    7    Ahmed Khan  38.0     NaN     Male
8    8    Rachel Lee  29.0     USA   Female
9    9   Carlos Ruiz   NaN  Mexico      NaN
10  10   Emily Davis  31.0     USA      NaN

In [5]:
# = 1 we have isna() or isnull() which returns true where it finds null value
data.isnull()

       id   name    age  country  gender
0   False  False  False    False   False
1   False  False  False    False   False
2   False  False   True    False   False
3   False  False   True    False   False
4   False  False  False    False   False
5   False  False  False    False   False
6   False   True  False    False   False
7   False  False  False     True   False
8   False  False  False    False   False
9   False  False   True    False    True
10  False  False  False    False    True

In [6]:
# Similar we can use isna()
data.isna()

       id   name    age  country  gender
0   False  False  False    False   False
1   False  False  False    False   False
2   False  False   True    False   False
3   False  False   True    False   False
4   False  False  False    False   False
5   False  False  False    False   False
6   False   True  False    False   False
7   False  False  False     True   False
8   False  False  False    False   False
9   False  False   True    False    True
10  False  False  False    False    True

In [8]:
# we can use isna().sum() to see the num of entries which is an empty in the datafra

data.isna().sum()

id         0
name       1
age        3
country    1
gender     2
dtype: int64

In [9]:
#- we aslo have an Option of replacing null values with some same values
#- mainly we replace it with mean,median and mode


data.fillna(0)

    id          name   age country   gender
0    1      John Doe  29.0     USA     Male
1    1      John Doe  29.0     USA     Male
2    2    Jane Smith   0.0  Canada   Female
3    3          Alex   0.0     USA  Unknown
4    4  Maria Garcia  34.0   Spain   Female
5    5        Li Wei  27.0   China     Male
6    6             0  45.0   India   Female
7    7    Ahmed Khan  38.0       0     Male
8    8    Rachel Lee  29.0     USA   Female
9    9   Carlos Ruiz   0.0  Mexico        0
10  10   Emily Davis  31.0     USA        0

In [12]:
# - we have an Option to drop the entries where we have the null Values

#- Dropna drop the rows where we have null Values
data.dropna()

   id          name   age country  gender
0   1      John Doe  29.0     USA    Male
1   1      John Doe  29.0     USA    Male
4   4  Maria Garcia  34.0   Spain  Female
5   5        Li Wei  27.0   China    Male
8   8    Rachel Lee  29.0     USA  Female

In [13]:
#to drop the cols we just need to add an axies
data.dropna(axis=1)

    id
0    1
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10

In [15]:
# we can aslo replace the values for the Particular Colms here 
age_mean=data["age"].mean()
data["age"].fillna(age_mean)

0     29.00
1     29.00
2     32.75
3     32.75
4     34.00
5     27.00
6     45.00
7     38.00
8     29.00
9     32.75
10    31.00
Name: age, dtype: float64

In [16]:
# - when we print the original data

In [17]:
data

    id          name   age country   gender
0    1      John Doe  29.0     USA     Male
1    1      John Doe  29.0     USA     Male
2    2    Jane Smith   NaN  Canada   Female
3    3          Alex   NaN     USA  Unknown
4    4  Maria Garcia  34.0   Spain   Female
5    5        Li Wei  27.0   China     Male
6    6           NaN  45.0   India   Female
7    7    Ahmed Khan  38.0     NaN     Male
8    8    Rachel Lee  29.0     USA   Female
9    9   Carlos Ruiz   NaN  Mexico      NaN
10  10   Emily Davis  31.0     USA      NaN

In [28]:
#it has all the null values so what we can do we can create a 
# new Df where we will have a Clean Data

cleaned_Data=data.copy()
Mean=cleaned_Data["age"].mean()

cleaned_Data["age"]=cleaned_Data["age"].fillna(Mean)
cleaned_Data


data

# fill -->Forword fill

data.ffill()

    id          name   age country   gender
0    1      John Doe  29.0     USA     Male
1    1      John Doe  29.0     USA     Male
2    2    Jane Smith  34.0  Canada   Female
3    3          Alex  34.0     USA  Unknown
4    4  Maria Garcia  34.0   Spain   Female
5    5        Li Wei  27.0   China     Male
6    6    Ahmed Khan  45.0   India   Female
7    7    Ahmed Khan  38.0     USA     Male
8    8    Rachel Lee  29.0     USA   Female
9    9   Carlos Ruiz  31.0  Mexico      NaN
10  10   Emily Davis  31.0     USA      NaN

In [31]:
# bfill ->backword fill

x=data.bfill()

In [32]:
# this is all the 
x

    id          name   age country   gender
0    1      John Doe  29.0     USA     Male
1    1      John Doe  29.0     USA     Male
2    2    Jane Smith  34.0  Canada   Female
3    3          Alex  34.0     USA  Unknown
4    4  Maria Garcia  34.0   Spain   Female
5    5        Li Wei  27.0   China     Male
6    6    Ahmed Khan  45.0   India   Female
7    7    Ahmed Khan  38.0     USA     Male
8    8    Rachel Lee  29.0     USA   Female
9    9   Carlos Ruiz  31.0  Mexico      NaN
10  10   Emily Davis  31.0     USA      NaN

In [33]:
# this is all the functions we use to handle missing values

Case	
Row-wise duplicates
df.duplicated()
Specific column	
df.duplicated(subset=['col'])
Column values	
df['col'].duplicated()
Column-wise duplicates
df.T.duplicated()
Get duplicate rows	
df[df.duplicated()]
Get all duplicates
df[df.duplicated(keep=False)]

In [1]:
df2=df

NameError: name 'df' is not defined

In [ ]:
df2