In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("employee.csv")
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   52000

In [6]:
df.head()

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [7]:
df.head(2)

   ID   Name  Age Department  Salary
0   1  Alice   25         HR   55000
1   2    Bob   32         IT   72000

In [8]:
df.tail()

   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   52000

In [9]:
df.tail(2)

   ID   Name  Age Department  Salary
8   9    Ian   35         IT   75000
9  10  Julia   30    Finance   52000

In [10]:
df.sample()

   ID   Name  Age Department  Salary
9  10  Julia   30    Finance   52000

In [11]:
df.sample(3)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
6   7    Grace   41         HR   82000
2   3  Charlie   28    Finance   48000

In [12]:
df.info

<bound method DataFrame.info of    ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   52000>

In [14]:
df.describe()

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  63700.000000
std     3.02765   6.674162  15649.281134
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  50500.000000
50%     5.50000  31.000000  60000.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [15]:
df.columns

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='object')

In [17]:
df.nunique()

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64